name: Build Only

on:
  push:
    branches:
      - main # or whichever branch you want
  pull_request: # optional: build on PRs too
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: npm install
        working-directory: client

      - name: Build frontend
        run: npm run build
        working-directory: client

      - name: Build executable (Mac/Linux)
        if: runner.os != 'Windows'
        run: uv run pyinstaller --onefile --add-data "server/static:static" server/app.py --name pebbleproductivityapp

      - name: Build executable (Windows)
        if: runner.os == 'Windows'
        run: uv run pyinstaller --onefile --add-data "server/static;static" server/app.py --name pebbleproductivityapp

      - name: Prepare artifacts per OS
        run: |
          mkdir upload
          if [ "$RUNNER_OS" = "Windows" ]; then
            cp dist/*.exe upload/app-$RUNNER_OS.exe
          else
            cp dist/* upload/app-$RUNNER_OS
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: upload/*
